### PR TITLE
feat: make all event/command snips async

### PR DESCRIPTION
**Pull request by Peter-MJ-Parker**
Made each snippet asynchronous

### CODE REVIEW

**Comment by EvolutionX-10** [comment]
Shouldn't we keep async as well as non async snippets?

**Comment by Peter-MJ-Parker** [comment]
I was wondering why they weren't async considering most functions inside of each event actually return a promise. 
ClientReady -by default no promises

MessageCreate - message.reply()/message.channel.send() return promises although most people don't await them

Commands - ctx.reply() returns a promise but people don't always await them. 

I just think it's good practice to use asynchronous functions when most of their methods return a promise.

**Comment by SrIzan10** [comment]
> Shouldn't we keep async as well as non async snippets?

I guess so. I actually thought the snippets were already async lol

**Review by SrIzan10 — APPROVED** [review]

**Comment by SrIzan10** [comment]
shitty hotel wifi didn't merge the PR lol

**Pull request merged**
